### ISSUE TITLE
Need to mannully update notification service label selector

### ISSUE THREAD

**Issue by brucexyz1234** [IBMStockTrader/notification-slack#4]
initially, it can not receive message,  and the messaging service complained timeout connecting to notification service.
after checked, found that :
the notification service have no endpoint, means it will not send traffic to notification (slack or twitter) pods.
the root cause is the  notification service have selector label app:notification
and the notification-slack pod label is app:nofitication-slack
after checked the service selector to app:notification-slack, it will work.

**Comment by jwalcorn** [comment]
Fixed this in the operator long ago.  I highly recommend using the operator (in the https://github.com/IBMStockTrader/stocktrader-operator repo) to install Stock Trader, rather than doing manual yaml.  At a minimum, start from the yaml in the operator repo if you need to install stuff manually, as I'm no longer maintaining separate yaml in each microservice repo.
